### ISSUE TITLE
Content Print Feature

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/ai-experience-sharing-platform#294]
Short Description:
Ability to print content (use cases and guide) that is styled and optimized for printing (or download a PDF). 
Are there any security concerns with printing a use case considering that only logged in users can access this content?

User Story: TBD
Acceptance Criteria: TBD

**Comment by sbabitch** [comment]
Renata, good question on security. I'm checking with Richard Speidel, GSA Chief Privacy Officer, for any concerns. For the Guide, I don't see an issue, as it's publicly facing (unless I'm missing something).

**Comment by jonadecker** [comment]
Closing because print styles is complete. Larger print (chapters/book) are detailed in separate Issues
