### ISSUE TITLE
SPIKE: UCL IA

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/ai-experience-sharing-platform#491]
As a team member, in order to determine what changes need to happen to the current UCL site IA, I want to better understand what content will live on UCL site and its vision.
============= or ===============
As someone new to the platform site, in order to know what resources are available to me, I want to understand what kinds of content are available on the site.

[AI CoE Newsletter](https://docs.google.com/document/d/1mqp2i5CDkgZ3ebJgBoQlX11PNuCXHJdvfKBrTUtfMx0/edit#heading=h.xdceeld7p2no)

Acceptance Criteria:
- [X] Meet with PO
- [x] Mindmap AI spaces
- [x] Suggest revised IA: https://app.mural.co/invitation/mural/flexion6734/1626380597578?sender=u52abf554822b710218084610&key=fec87f77-85c9-4015-8220-0fb161d4bf10

**Comment by sknep** [comment]
Updates on this available here: https://app.mural.co/t/flexion6734/m/flexion6734/1626380597578/8a9412fce03bc972192798dc3b20d664d1c6943d?sender=u13412568014516bea2a48526

Feedback welcome!

**Comment by r-bartlett-gsa** [comment]
Proposed and approved IA: ![AI-IA 7-21-21_1](https://user-images.githubusercontent.com/66442872/126656009-aca94003-784a-4770-966c-4af82a5d7dce.png)
