### ISSUE TITLE
UCL Site Design Updates - Homepage and Main Nav

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/ai-experience-sharing-platform#561]
As a UCL site user, in order to have a positive experience while browsing UCL site, I want to site design and layout to be intuitive, clear and consistent.

Acceptance Criteria / Tasks:

- [x] Approved home page and main nav designs are implemented

**Comment by r-bartlett-gsa** [comment]
![AI-1](https://user-images.githubusercontent.com/66442872/128068362-72e92851-d5e0-4956-832c-cd4742aa38de.png)
![AI-2](https://user-images.githubusercontent.com/66442872/128068400-1e3ec41d-db44-46df-9e77-e76bc2a9e664.png)
![AI-3](https://user-images.githubusercontent.com/66442872/128068410-353658bb-e68e-45b6-a89d-75b068930764.png)

**Comment by r-bartlett-gsa** [comment]
Also see SPIKE card #410

**Comment by sknep** [comment]
Update - The homepage is ready to merge but the nav is yet to come. see https://github.com/GSA/ai-experience-sharing-platform/pull/560

**Comment by sknep** [comment]
Update -- partial complete here. Rebuilding the nav to have dropdowns and be mobile friendly requires a little more rework, but so far I've added the login prompt which matches icons that show up later indicating which content is behind auth:
<img width="1453" alt="Screen Shot 2021-08-10 at 3 28 53 PM" src="https://user-images.githubusercontent.com/4451344/128930791-15178422-c414-45eb-b483-6f6de0c8e3cd.png">
<img width="1465" alt="Screen Shot 2021-08-10 at 3 29 02 PM" src="https://user-images.githubusercontent.com/4451344/128930798-bbb64e8b-97b2-40e3-91d2-cc58b963dd90.png">
<img width="1137" alt="Screen Shot 2021-08-10 at 3 31 09 PM" src="https://user-images.githubusercontent.com/4451344/128930800-814276ae-1335-47bd-b01d-5664c10daeec.png">

**Comment by sknep** [comment]
Main nav updates including a login prompt deployed here: https://github.com/GSA/ai-experience-sharing-platform/pull/591

We ended up not totally reworking the nav in the interests of time, as the current one-row nav works fine so long as there aren't too many top-level items added. Conversations about this earlier this week said:
> looking at the screenshots in this thread, like you said, it doesn't feel 'wrong' at all.
and
>I’m game for the most efficient solve
